version: "3"
services:
  nginx:
    container_name: nginx
    image: docker.io/nginx:alpine
    ports:
      - "80:80"
    volumes:
      - "/home/user/docker/deployments/config/nginx.conf:/etc/nginx/nginx.conf"
    restart: always
    depends_on:
      - project-web
      - minio
      - frontend

  project-web:
    container_name: project-web
    restart: always
    image: ghcr.io/last-summer-project/project-web:latest
    expose:
      - 8080
    volumes:
      # this is cursed way but who cares :<
      - "/home/user/docker/deployments/config/application.properties:/workspace/BOOT-INF/classes/application.properties"
    depends_on:
      - mariadb
      - minio

  frontend:
    container_name: frontend
    restart: always
    image: ghcr.io/last-summer-project/frontend:latest
    expose:
      - 4200

  mariadb:
    container_name: mariadb
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    expose:
      - 3306
    ports:
      - "0.0.0.0:3307:3306"
    volumes:
      - "/home/user/docker/mysql_data:/config"
    image: "lscr.io/linuxserver/mariadb:10.6.13"

  minio:
    container_name: minio
    command: server /data --console-address ":9001"
    restart: always
    ports:
      - "0.0.0.0:9000:9000"
      - "0.0.0.0:9001:9001"
    volumes:
      - "/home/user/docker/minio_data:/data"
    image: quay.io/minio/minio:latest
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3

  timelapse-server:
    container_name: timelapse-server
    restart: always
    image: ghcr.io/last-summer-project/timelapse-server:latest
    volumes:
      - "/home/user/docker/deployments/config/env.env:/project/.env"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    depends_on:
      - mariadb
      - minio

  detect-server:
    container_name: detect-server
    restart: always
    image: ghcr.io/last-summer-project/detect-server:latest
    volumes:
      - "/home/user/docker/deployments/config/env.env:/project/.env"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    depends_on:
      - mariadb
      - minio

  watchtower:
    container_name: watchtower
    image: docker.io/containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup